name: API Update
on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v1
        name: Configure AWS credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Node.js setup
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build
        run: |
          npm run build
      - name: Lambda code update
        run: |
          aws lambda update-function-code --function-name test-lambda-ts --zip-file fileb://./dist/api.zip
